from flask import Flask, send_from_directory
from routes.inventory  import inventory_bp
from routes.jobs       import jobs_bp
from routes.computers  import computers_bp
from routes.packages   import packages_bp
from routes.config     import config_bp
from datetime import timedelta
from auth import auth_bp, init_auth
from dotenv import load_dotenv
import os

load_dotenv()

app = Flask(__name__)

secret = os.environ.get('FLASK_SECRET_KEY')
if not secret:
    raise RuntimeError("FLASK_SECRET_KEY not set in .env — refusing to start")
app.secret_key = secret
app.permanent_session_lifetime = timedelta(hours=8)

app.register_blueprint(auth_bp)
app.register_blueprint(inventory_bp)
app.register_blueprint(jobs_bp)
app.register_blueprint(computers_bp)
app.register_blueprint(packages_bp)
app.register_blueprint(config_bp)
init_auth(app)


@app.route("/")
def index():
    return send_from_directory(".", "templates/dashboard.html")

if __name__ == "__main__":
    app.run(
        host="0.0.0.0",
        port=5000,
        ssl_context=("server_cert.pem", "key.pem"),  # generated by generate_cert.py
        debug=False
    )
